#!/usr/bin/env python3
"""
img2logo.py - 将图片转换为 Eric301 LCD Logo C数组

用法:
    python3 tools/img2logo.py <input_image> [output_file]

示例:
    python3 tools/img2logo.py logo.png                    # 输出到终端
    python3 tools/img2logo.py logo.png User/logo_data.h   # 输出到文件

输入: 任意格式图片 (PNG/BMP/JPG)，自动缩放到 128x64 并转为黑白二值
输出: C语言头文件，包含 logo[1040] 数组（兼容 ST7565R 页模式）

注意: 需要安装 Pillow: pip3 install Pillow
"""

import sys
import os

def convert_image_to_logo(input_path, output_file=None):
    try:
        from PIL import Image
    except ImportError:
        print("错误: 需要安装 Pillow 库")
        print("运行: pip3 install Pillow")
        sys.exit(1)

    if not os.path.exists(input_path):
        print(f"错误: 文件不存在 - {input_path}")
        sys.exit(1)

    # 加载图片，转为黑白二值，缩放到 128x64
    img = Image.open(input_path).convert('L')  # 先转灰度
    img = img.resize((128, 64), Image.LANCZOS)
    img = img.point(lambda x: 0 if x < 128 else 255, '1')  # 二值化

    lines = []
    lines.append("/* Auto-generated by img2logo.py */")
    lines.append(f"/* Source: {os.path.basename(input_path)} */")
    lines.append("")
    lines.append("#ifndef _LOGO_DATA_H_")
    lines.append("#define _LOGO_DATA_H_")
    lines.append("")
    lines.append("#include \"stm8l15x.h\"")
    lines.append("")
    lines.append("/* Logo bitmap: 16-byte header + 128x64 pixels = 1040 bytes */")
    lines.append("/* ST7565R page mode: 8 pages x 128 columns, LSB=top */")
    lines.append("")
    lines.append("#if defined(_IAR_)")
    lines.append("#pragma location = 0x00F000")
    lines.append("#endif")
    lines.append("__ROOT const uint8_t logo[1040] = {")

    # 16字节文件头 (与原始 logo 格式兼容)
    lines.append("    /* Header (16 bytes) */")
    lines.append("    0x12, 0x34, 0x56, 0x78, 0x00, 0x00, 0x00, 0x00,")
    lines.append("    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,")
    lines.append("")

    # 转换为 ST7565R 页模式数据
    for page in range(8):
        lines.append(f"    /* Page {page} (rows {page*8}-{page*8+7}) */")
        row_data = []
        for col in range(128):
            byte_val = 0
            for bit in range(8):
                y = page * 8 + bit
                pixel = img.getpixel((col, y))
                if pixel == 0:  # 黑色像素 = LCD亮点
                    byte_val |= (1 << bit)
            row_data.append(f"0x{byte_val:02X}")

        # 每行16个字节
        for i in range(0, 128, 16):
            chunk = ", ".join(row_data[i:i+16])
            comma = "," if not (page == 7 and i + 16 >= 128) else ""
            lines.append(f"    {chunk}{comma}")
        lines.append("")

    lines.append("};")
    lines.append("")
    lines.append("#endif /* _LOGO_DATA_H_ */")
    lines.append("")

    output = "\n".join(lines)

    if output_file:
        with open(output_file, 'w') as f:
            f.write(output)
        print(f"✅ Logo 已生成: {output_file}")
        print(f"   尺寸: 128x64, {1040} bytes")
    else:
        print(output)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    convert_image_to_logo(input_path, output_file)
